# maint_update_ubuntu.yaml -i hosts --extra-vars \
#  "myhost=<specific host or group>"
- name: playbook to update pkgs and reboot AWS PROD exception server
  hosts: '{{ myhost  }}'
  tasks:

    - name: update packages on amzlnx1 server which allows sudo
      import_tasks: tasks/update_amzlnx1_dnf_sudo.yaml
      when: ansible_distribution == 'Amazon'

    - name: reboot server which allows sudo
      import_tasks: tasks/reboot_server_sudo.yaml
      when: ansible_distribution == 'Amazon'

    - name: update packages on amzlnx2 server which allows sudo
      import_tasks: tasks/update_amzlnx2_urllib3_sudo.yaml
      when: ansible_distribution == 'Amazon'

    - name: reboot server which allows sudo
      import_tasks: tasks/reboot_server_sudo.yaml
      when: ansible_distribution == 'Amazon'

