- name: collectd, cloudwatch, and post-setup AIO for service-admin server
  hosts: service-admin
  vars:
    my_hosts: service-admin
  tasks:
    - name: install collectd cloudwatch plugin
      import_tasks: tasks/install_collectd_cloudwatch_plugin_amazon_linux2.yaml
    - name: install cloudwatch-agent and configure
      import_tasks: tasks/install_amzn_cloudwatch_agent_ubuntu_generic.yaml
    - name: post-setup for collectd-cloudwatch
      import_tasks: tasks/collectd_cw_post_setup_generic.yaml
